common:
    exp_name: got10k_imagenet_resnet50_s3_test
   
    # Model related
    model_type: imagenet50
    remove_layers: ['layer4']
    im_mean: [0.485, 0.456, 0.406]
    im_std: [0.229, 0.224, 0.225]
    nopadding: False
    resume: None
    
    # Misc
    down_factor: 8
    infer2D: True 
    workers: 4
    gpu_id: [0,1,2,3]
    device: cuda

sot:
    dataset: 'GOT10K'
    dataroot: '/home/wangzd/datasets/GOT/GOT10k/'
    epoch_test: False

