common:
    exp_name: lasot_selav2_s3
   
    # Model related
    model_type: sela-v2 
    remove_layers: ['layer4']
    im_mean: [0.485, 0.456, 0.406]
    im_std: [0.229, 0.224, 0.225]
    nopadding: False
    resume: './weights/sela-v2.pth' 
    
    # Misc
    down_factor: 8
    infer2D: True 
    workers: 4
    gpu_id: [4,5,6,7]
    device: cuda

sot:
    dataset: 'LaSOT'
    dataroot: '/home/wangzd/datasets/GOT/LaSOT/'
    epoch_test: False

