common:
    exp_name: tlp_vfs_resnet50_s3
   
    # Model related
    model_type: vfs
    remove_layers: ['layer4']
    im_mean: [0.485, 0.456, 0.406]
    im_std: [0.229, 0.224, 0.225]
    nopadding: False
    resume: './weights/vfs/otb1.pth.tar' 
    
    # Misc
    down_factor: 8
    infer2D: True 
    workers: 4
    gpu_id: [4,5,6,7]
    device: cuda

sot:
    dataset: 'TLP'
    dataroot: '/home/wangzd/datasets/GOT/TLP/TLP/'
    epoch_test: False

